---
# Our data container, mainly for storing the Postgres container's database
# files. This will allow us to move between postgres versions without losing the
# data currently in our development environment.

# We won't worry if this container is not in a "running state" when you
# type 'docker-compose ps'.
data:
  image: tianon/true
  volumes: [ "/var/lib/postgresql/data" ]

# Our PostgreSQL service:
postgres:
  image: vovimayhem/postgis:2.1.7-9.4.4
  # Bind host port 5432 to PostgreSQL port 5432:
  ports: [ "5442:5432" ]
  # We're mounting 'db/dumps' into the postgres container so we can backup and
  # restore data dumps easily:
  volumes: [ "./db/dumps:/data-dumps" ]
  volumes_from: [ "data" ]
  environment:
    LC_ALL: C.UTF-8
    POSTGRES_PASSWORD: 41rqu4l1ty

# Our Redis service:
redis:
  image: redis:3.0.4
  # Bind host port 6389 to Redis port 6379:
  ports: [ "6389:6379" ]
  command: redis-server --appendonly yes

# Application: -----------------------------------------------------------------
gems: &app_base
  image: ruby:2.2.3
  volumes: [ ".:/usr/src/app", "/usr/local/bundle" ]
  working_dir: /usr/src/app
  environment: &app_environment
    PATH: /usr/src/app/bin:/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    DATABASE_URL: postgis://postgres:41rqu4l1ty@postgres.air-quality.local:5432/air_quality_development?pool=25&encoding=unicode&schema_search_path=public
    REDIS_URL: redis://redis.air-quality.local:6379/air_quality_development
    RACK_ENV: development
    RAILS_ENV: development
  links: [ "postgres:postgres.air-quality.local", "redis:redis.air-quality.local" ]
  env_file: [ "dev.env" ]

# We'll also use this configuration (&app_base) for the web and test
# containers:
jobs: &app
  <<: *app_base
  stdin_open: true
  tty: true
  volumes_from: [ "gems" ]
  entrypoint: /usr/src/app/dev-entrypoint.sh
  command: sidekiq -c 25 -q default

web:
  <<: *app
  ports: [ "3001:3000" ]
  command: rails server -p 3000 -b 0.0.0.0

# App Guard: Keeps running tests on a separate process:
test:
  <<: *app # We copy from &app_base, and override:
  command: guard start --no-bundler-warning --no-interactions --force-polling
  environment:
    <<: *app_environment
    DATABASE_URL: postgis://postgres:41rqu4l1ty@postgres.air-quality.local:5432/air_quality_test?pool=25&encoding=unicode&schema_search_path=public
    REDIS_URL: redis://redis.air-quality.local:6379/air_quality_test
    RACK_ENV: test
    RAILS_ENV: test
