glusterfs-server:
  image: rancher/glusterfs:v0.2.0
  command: /opt/rancher/peerprobe.sh container:glusterfs-server
  volumes_from: [ "glusterfs-data" ]
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: glusterfs-daemon,glusterfs-data,glusterfs-volume-create

glusterfs-daemon:
  image: rancher/glusterfs:v0.2.0
  command: "glusterd -p /var/run/gluster.pid -N"
  net: container:glusterfs-server
  cap_add: [ "SYS_ADMIN" ]
  volumes_from: [ "glusterfs-data" ]
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/glusterfs-server

glusterfs-volume-create:
  image: rancher/glusterfs:v0.2.0
  command: /opt/rancher/replicated_volume_create.sh container:glusterfs-server
  net: 'container:glusterfs-server'
  volumes_from: [ "glusterfs-data" ]
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true

#
# WARNING -- DO NOT CHANGE ANYTHING BELOW
# DATA LOSS!!!! CAN OCCURR DURING UPGRADE
#
glusterfs-data:
  image: rancher/glusterfs:v0.1.3
  command: /bin/true
  volumes: [ "/var/run" ]
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
