---
# Our data container, mainly for storing the Postgres container's database
# files. This will allow us to move between postgres versions without losing the
# data currently in our development environment.

# We won't worry if this container is not in a "running state" when you
# type 'docker-compose ps'.
data:
  image: tianon/true
  volumes: [ "/var/lib/postgresql/data" ]

# Our PostgreSQL service:
postgres:
  image: vovimayhem/postgis:2.1.8-9.4.4
  volumes_from: [ "data" ]
  restart: always
  environment:
    LC_ALL: C.UTF-8
    POSTGRES_PASSWORD: 41rqu4l1ty

# Our Redis service:
redis:
  image: redis:3.0.7
  command: redis-server --appendonly yes
  restart: always

# We'll also use this configuration (&app_base) for the web and test
# containers:
jobs: &app
  image: simanl/air-quality-rails:v6-rc6
  command: sidekiq -c 25 -q default
  restart: always
  stdin_open: true
  tty: true
  links:
    - postgres:postgres.air-quality.local
    - redis:redis.air-quality.local
  environment: &app_env
    DATABASE_URL: postgis://postgres:41rqu4l1ty@postgres.air-quality.local:5432/air_quality_staging?pool=25&encoding=unicode&schema_search_path=public
    REDIS_URL: redis://redis.air-quality.local:6379/air_quality_staging
    FORECAST_ENGINE_URL: tcp://104.236.145.13:6311
    SECRET_KEY_BASE: f6c8303a92658b08b79e275e4d3888c9bf5ff40505c84344a2013fa574b3b4fd5144c2477caa19a382288e1e9e8929760764f53c9d83133970f77b8bd7e281fe
    LOG_LEVEL: DEBUG


web:
  <<: *app
  ports:
    - "80:80"
  command: /usr/bin/supervisord --configuration=/usr/src/app/config/supervisord-web.conf
  environment:
    <<: *app_env
    PUMA_MIN_THREADS: 8
    PUMA_MAX_THREADS: 12
    PUMA_WORKERS: 2
