pull_data_from_sima:
  # you can use rufus-scheduler "every" syntax in place of cron if you prefer
  every:
    - 10m
    - first_in: 10s
  # By default the job name (hash key) will be taken as worker class name.
  # If you want to have a different job name and class name, provide the 'class' option
  class: PullDataFromSimaJob
  queue: default
  description: "Updates measurements from SIMA NL web service"

# update_forecasts:
#   cron: "5 6,12,18 * * *"
#   # By default the job name (hash key) will be taken as worker class name.
#   # If you want to have a different job name and class name, provide the 'class' option
#   class: UpdateForecastsJob
#   queue: forecasting
#   description: "Updates measurements from SIMA NL web service"
