# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 093772228d013392592ebca79b434ad7ac586eaa11f482d29ea7e5a4b659b48bc0af6068fa07e0073c72ddc8eae49f8b368e84a116b46b39320c4499e94e6661

test:
  secret_key_base: 9da30b48c3da574aeecd9e785882bb2da67f6314a0a0b94d236b9b8da676c4cac841d369c8c57286033da2d47889f8555beaf1f02072f2aee1076511b026a766

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
