---
# The postgres service will use an existing storage pool in the rancher farm:
postgres:
  environment:
    LC_ALL: C.UTF-8
    POSTGRES_PASSWORD: 41rqu4l1ty
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: data-server=true,convoy.glusterfs=true
  tty: true
  image: vovimayhem/postgis:2.1.8-9.4.4
  volumes:
    - airdb:/var/lib/postgresql/data
  stdin_open: true
  volume_driver: convoy-gluster

# The Redis service will also use the existing storage pool in the rancher farm:
redis:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: data-server=true,convoy.glusterfs=true
  tty: true
  command: redis-server --appendonly yes
  image: redis:3.0.7
  volumes:
  - airkeyval:/data
  stdin_open: true
  volume_driver: convoy-gluster

# The Job Processor app:
jobs:
  tty: true
  image: simanl/air-quality-rails:v6-rc7
  links:
    - postgres:postgres.air-quality.local
    - redis:redis.air-quality.local
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: app-server=true
  command: sidekiq -c 25 -q default
  stdin_open: true
  environment:
    DATABASE_URL: postgis://postgres:41rqu4l1ty@postgres.air-quality.local:5432/air_quality_staging?pool=25&encoding=unicode&schema_search_path=public
    REDIS_URL: redis://redis.air-quality.local:6379/air_quality_staging
    FORECAST_ENGINE_URL: tcp://forecasts.air-quality.local:6311
    SECRET_KEY_BASE: f6c8303a92658b08b79e275e4d3888c9bf5ff40505c84344a2013fa574b3b4fd5144c2477caa19a382288e1e9e8929760764f53c9d83133970f77b8bd7e281fe

# The Web + API app:
web:
  tty: true
  image: simanl/air-quality-rails:v6-rc7
  links:
    - postgres:postgres.air-quality.local
    - redis:redis.air-quality.local
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: app-server=true
  command: /usr/bin/supervisord --configuration=/usr/src/app/config/supervisord-web.conf
  stdin_open: true
  environment:
    DATABASE_URL: postgis://postgres:41rqu4l1ty@postgres.air-quality.local:5432/air_quality_staging?pool=25&encoding=unicode&schema_search_path=public
    REDIS_URL: redis://redis.air-quality.local:6379/air_quality_staging
    FORECAST_ENGINE_URL: tcp://forecasts.air-quality.local:6311
    SECRET_KEY_BASE: f6c8303a92658b08b79e275e4d3888c9bf5ff40505c84344a2013fa574b3b4fd5144c2477caa19a382288e1e9e8929760764f53c9d83133970f77b8bd7e281fe
    PUMA_MIN_THREADS: 8
    PUMA_MAX_THREADS: 12
    PUMA_WORKERS: 2

# The Web app + API load balancer:
web-lb:
  tty: true
  image: rancher/load-balancer-service
  links:
    - web:web
  ports:
    - 80:80
  labels:
    io.rancher.scheduler.affinity:host_label: has-public-ip=true
  stdin_open: true
